begin;

create table if not exists public.casopisy (
  id bigint generated by default as identity primary key,
  rok_platnosti integer not null,
  nazev text not null,
  issn text not null default '',
  eissn text not null default '',
  kategorie text,
  ais_hodnota numeric,
  ais_kvartal text,
  jif_hodnota numeric,
  jif_kvartal text,
  jif_percentil numeric,
  zdroj_soubor text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists casopisy_uq_rok_ident
  on public.casopisy (rok_platnosti, issn, eissn, nazev);

create index if not exists casopisy_idx_rok on public.casopisy (rok_platnosti);
create index if not exists casopisy_idx_issn on public.casopisy (issn);
create index if not exists casopisy_idx_eissn on public.casopisy (eissn);

alter table public.casopisy enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update on table public.casopisy to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists casopisy_authenticated_select on public.casopisy;
create policy casopisy_authenticated_select
on public.casopisy
for select
to authenticated
using (true);

drop policy if exists casopisy_authenticated_insert on public.casopisy;
create policy casopisy_authenticated_insert
on public.casopisy
for insert
to authenticated
with check (true);

drop policy if exists casopisy_authenticated_update on public.casopisy;
create policy casopisy_authenticated_update
on public.casopisy
for update
to authenticated
using (true)
with check (true);

commit;
